# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-03 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0017_group_main_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='group',
            name='favorite_dancing_songs',
            field=models.TextField(blank=True),
        ),
    ]
