# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-03 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0018_add_group_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Any additional comments?'),
        ),
        migrations.AlterField(
            model_name='group',
            name='favorite_dancing_songs',
            field=models.TextField(blank=True, verbose_name="What's your favorite songs to dance to?"),
        ),
        migrations.AlterField(
            model_name='person',
            name='dietary_restrictions',
            field=models.CharField(max_length=255),
        ),
    ]
