# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-17 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0019_expand_names_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dietary_restrictions',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
