# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0020_auto_20181117_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='main_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
