# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0022_changed_my_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='group',
            name='address_country',
        ),
        migrations.RemoveField(
            model_name='group',
            name='address_postal_code',
        ),
        migrations.RemoveField(
            model_name='group',
            name='address_state_province',
        ),
        migrations.AddField(
            model_name='group',
            name='address_3',
            field=models.CharField(blank=True, max_length=80, verbose_name=b'Adress Line 3'),
        ),
        migrations.AddField(
            model_name='group',
            name='changes',
            field=models.TextField(blank=True, verbose_name=b'Any changes to your information above not captured by the form?'),
        ),
    ]
