# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-19 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0023_changed_address_add_change_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='pnr',
            field=models.CharField(max_length=20, unique=True, verbose_name=b'Confirmation Code'),
        ),
    ]
