# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-01 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0024_auth_len'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where_stay', models.IntegerField(choices=[(1, b'No Response'), (2, b"I'd like to stay at the camp, in one of the vintage bunk beds."), (3, b"I'm getting a hotel block, as described on the website"), (4, b"I'd like to stay at the camp in a tent (that I bring)"), (5, b"I'll be staying somewhere else, don't worry about it!")], default=1)),
                ('camp_options_party', models.BooleanField(default=False, verbose_name=b'I plan on partying either until the sun rises or my body yells "hey! get some rest!"')),
                ('camp_options_reasonable', models.BooleanField(default=False, verbose_name=b'I love weddings, but I still need to get to bed at a reasonable hour.')),
                ('camp_options_heavy_sleeper', models.BooleanField(default=False, verbose_name=b'I am a heavy sleeper.')),
                ('camp_options_light_sleeper', models.BooleanField(default=False, verbose_name=b'I am a light sleeper.')),
                ('camp_options_bathroom', models.BooleanField(default=False, verbose_name=b'I need the bathroom that I use to be in the same building as I sleep.')),
                ('camp_options_ac', models.BooleanField(default=False, verbose_name=b'I need air conditioning.')),
                ('number_of_rides', models.IntegerField(default=0, verbose_name=b'How many people in your group would like a ride up the hill to the ceremony and back down at the conclusion?')),
                ('number_of_seated', models.IntegerField(default=0, verbose_name=b'How many people in your group would like to sit throughout the ceremony?')),
                ('other_mobility', models.TextField(verbose_name=b"Are there other mobility questions that we aren't considering that we should be aware of?")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.Group')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='dietary_restrictions',
            field=models.IntegerField(choices=[(1, b'None'), (2, b'Vegetarian'), (3, b'Vegan'), (4, b'Kosher'), (5, b'Gluten Free'), (6, b'Other')], default=1),
        ),
    ]
