# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-01 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0025_changed_my_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupoptions',
            name='has_reviewed',
            field=models.BooleanField(default=False, verbose_name=b'I have reviewed these questions and are all set with our answers!'),
        ),
    ]
