# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-01 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0026_groupoptions_has_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupoptions',
            name='other_mobility',
            field=models.TextField(blank=True, verbose_name=b"Are there other mobility questions that we aren't considering that we should be aware of?"),
        ),
    ]
